# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb0\x01\n\x04\x44\x65mo\x12\x32\n\x11GetServerResponse\x12\r.demo.Request\x1a\x0e.demo.Response\x12<\n\x19GetMultipleServerResponse\x12\r.demo.Request\x1a\x0e.demo.Response0\x01\x12\x36\n\x15GetServerResponseJSON\x12\r.demo.Request\x1a\x0e.demo.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=46
  _globals['_RESPONSE']._serialized_start=48
  _globals['_RESPONSE']._serialized_end=75
  _globals['_DEMO']._serialized_start=78
  _globals['_DEMO']._serialized_end=254
# @@protoc_insertion_point(module_scope)
