# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\x1b\n\x0bTaskRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\tTasksList\x12\r\n\x05tasks\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2i\n\x0bTodoService\x12\x30\n\x07\x41\x64\x64Task\x12\x11.todo.TaskRequest\x1a\x12.todo.TaskResponse\x12(\n\x08GetTasks\x12\x0b.todo.Empty\x1a\x0f.todo.TasksListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKREQUEST']._serialized_start=20
  _globals['_TASKREQUEST']._serialized_end=47
  _globals['_TASKRESPONSE']._serialized_start=49
  _globals['_TASKRESPONSE']._serialized_end=80
  _globals['_TASKSLIST']._serialized_start=82
  _globals['_TASKSLIST']._serialized_end=108
  _globals['_EMPTY']._serialized_start=110
  _globals['_EMPTY']._serialized_end=117
  _globals['_TODOSERVICE']._serialized_start=119
  _globals['_TODOSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
